apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

images:
  - name: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/pipelines-vote-api
    newTag: v0
